# Core Colors
background            #1a120d
foreground            #f0dfd7
selection_foreground  #ffb68e
selection_background  #532201
cursor                #ffb68e
cursor_text_color     #1a120d

# Regular Colors
color0  #1a120d
color1  #ffb4ab
color2  #ffb68e
color3  #cdc991
color4  #ffdbca
color5  #ffdbca
color6  #e6beaa
color7  #f0dfd7

# Bright Colors
color8  #413732
color9  #ffb4ab
color10 #ffb68e
color11 #cdc991
color12 #ffdbca
color13 #ffdbca 
color14 #e6beaa
color15 #f0dfd7
